export const platformFlows = [
  {
    id: "platform-auth-tokens",
    title: "Authentication & token refresh",
    prdScreens: "§7 Auth #3",
    summary: "Token-based auth with short-lived access tokens and refresh flow.",
    role: "admin",
    surface: "api",
    steps: [
      { id: "s1", label: "Login", detail: "Invite or Partner code exchange.", events: ["login"] },
      { id: "s2", label: "Access token", detail: "Short-lived JWT or equivalent.", wireframeId: "login" },
      { id: "s3", label: "Refresh", detail: "Silent refresh before expiry.", wireframeId: "login" },
    ],
  },
  {
    id: "platform-entitlement",
    title: "Entitlement & catalog filter",
    prdScreens: "§7 Library · §10 API",
    summary: "Every catalog request filtered by Admin → Partner → Listener chain.",
    role: "admin",
    surface: "api",
    steps: [
      { id: "s1", label: "Auth context", detail: "listener_id + partner_id.", events: ["login"] },
      { id: "s2", label: "Entitlement fetch", detail: "Allowed Session IDs + offline flags.", wireframeId: "library" },
      { id: "s3", label: "Signed stream URL", detail: "CDN tokenized delivery.", wireframeId: "player", events: ["play_start"] },
    ],
    requirements: ["TLS everywhere", "Tokenized CDN URLs"],
  },
  {
    id: "platform-revoke",
    title: "Revoke cascade",
    prdScreens: "§7 Auth #4 · §9 Security #6",
    summary: "Rapid revoke for users, Partners, or assets.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "Revoke trigger", detail: "Admin or Partner action.", wireframeId: "admin-people" },
      { id: "s2", label: "Stream invalidate", detail: "Active URLs rejected.", wireframeId: "error-revoked" },
      { id: "s3", label: "Offline invalidate", detail: "License checks fail.", wireframeId: "error-revoked" },
    ],
  },
  {
    id: "platform-acquisition-funnel",
    title: "Acquisition analytics funnel",
    prdScreens: "§8 Acquisition",
    summary: "Invite → accept → first login timing by Partner.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "invite_sent", detail: "Per Partner provisioning.", events: ["invite_sent"] },
      { id: "s2", label: "invite_accepted", detail: "Redemption rate.", events: ["invite_accepted"] },
      { id: "s3", label: "login", detail: "Time invite → first login.", events: ["login"] },
    ],
  },
  {
    id: "platform-engagement-funnel",
    title: "Engagement analytics funnel",
    prdScreens: "§8 Engagement",
    summary: "Acceptance → first complete listen → second session latency.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "session_view", detail: "Catalog engagement.", events: ["session_view"] },
      { id: "s2", label: "play_start → play_complete", detail: "Completion rates.", events: ["play_start", "play_complete"] },
      { id: "s3", label: "Second session", detail: "First-to-second latency.", events: ["play_complete"] },
    ],
  },
  {
    id: "platform-retention",
    title: "Retention & satisfaction",
    prdScreens: "§8 Retention",
    summary: "LTD listens, period trends, qualitative feedback.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "Listen totals", detail: "Per user period + lifetime.", wireframeId: "admin-dashboard" },
      { id: "s2", label: "Frequency trend", detail: "MAU/WAU style cadence.", wireframeId: "admin-dashboard" },
      { id: "s3", label: "Feedback", detail: "App + Session qualitative.", wireframeId: "admin-feedback", events: ["feedback_submitted_session"] },
    ],
  },
  {
    id: "platform-seat-metering",
    title: "Seat pool metering",
    prdScreens: "§8 Partner & Billing #e",
    summary: "Included, consumed, peak concurrent, overage seats for site licenses.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "seat_allocated", detail: "Listener activates seat.", events: ["seat_allocated"] },
      { id: "s2", label: "Peak tracking", detail: "Concurrent active seats.", wireframeId: "admin-billing" },
      { id: "s3", label: "seat_released", detail: "Revoke or pause frees seat.", events: ["seat_released"] },
    ],
  },
  {
    id: "platform-security-hardening",
    title: "Security validation flows",
    prdScreens: "§12 Test Plan · §9 Security",
    summary: "Jailbreak detection, leak attempts, token expiry, recording API limits.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "Jailbreak/root", detail: "Graceful denial.", wireframeId: "error-revoked" },
      { id: "s2", label: "Leak attempt", detail: "Signed URL sharing fails.", wireframeId: "error-revoked" },
      { id: "s3", label: "Token expiry", detail: "Mid-stream invalidation handled.", wireframeId: "error-network" },
    ],
  },
  {
    id: "platform-privacy-deletion",
    title: "Privacy & data deletion",
    prdScreens: "§9 Privacy",
    summary: "Data minimization; retention/deletion pathways; regional storage.",
    role: "listener",
    surface: "mobile",
    steps: [
      { id: "s1", label: "Request", detail: "From support / privacy flow.", wireframeId: "privacy-request" },
      { id: "s2", label: "Admin process", detail: "Documented deletion pathway.", wireframeId: "admin-people" },
    ],
    openQuestions: ["GDPR/CCPA formal requirements"],
  },
  {
    id: "platform-crash-reporting",
    title: "Crash reporting & triage",
    prdScreens: "§9 Reliability #3",
    summary: "Integrated crash reporting for pilot stability criterion.",
    role: "admin",
    surface: "platform",
    steps: [
      { id: "s1", label: "Client crash", detail: "Automatic report from app.", wireframeId: "error-network" },
      { id: "s2", label: "Triage", detail: "Ops review before store release.", wireframeId: "admin-dashboard" },
    ],
  },
];
