import {
  WfSplash,
  WfDiscover,
  WfGetStarted,
  WfInvitation,
  WfAccessCode,
  WfAuthSuccess,
  WfCheckIn,
  WfHeadphones,
  WfPublicListening,
  WfExperienced,
  WfScienceHome,
  WfTopicDetail,
  WfRequestAccess,
  WfRequestSubmitted,
  WfReturningHome,
  WfOnboarding,
  WfGuidance,
  WfNeurotype,
  WfProfile,
  WfOnboardingComplete,
  WfLibrary,
  WfFavorites,
  WfSessionDetail,
  WfPlayer,
  WfCompletion,
  WfCompletionReflection,
  WfFeedback,
  WfAbout,
  WfSettings,
  WfSupport,
  WfResearch,
  WfError,
  WfSystemLoading,
  WfPartnerLogin,
  WfPartnerDashboard,
  WfPartnerListenerDetail,
  WfAdminTable,
} from "./screens.jsx";

/** @param {React.ComponentType} Screen @param {object} [props] @param {object} [meta] */
function entry(Screen, props = {}, meta = {}) {
  return { Screen, props, ...meta };
}

const DESKTOP_FRAME = { frame: "desktop" };

export const WIREFRAME_REGISTRY = {
  splash: entry(WfSplash),
  "pv-discover": entry(WfDiscover),
  "pv-get-started": entry(WfGetStarted),
  "pv-public-landing": entry(WfGetStarted, { variant: "public" }),
  "pv-invitation": entry(WfInvitation),
  "pv-check-in": entry(WfCheckIn, { variant: "before" }),
  "pv-reflection": entry(WfCheckIn, { variant: "after" }),
  "pv-headphones": entry(WfHeadphones),
  "pv-listening": entry(WfPublicListening),
  "pv-listening-alt": entry(WfPlayer, { variant: "interrupted" }),
  "pv-experienced": entry(WfExperienced),
  "pv-science-home": entry(WfScienceHome),
  "pv-topic-detail": entry(WfTopicDetail),
  "pv-request-access": entry(WfRequestAccess),
  "pv-request-submitted": entry(WfRequestSubmitted),
  "pv-returning-home": entry(WfReturningHome),
  login: entry(WfAccessCode, { variant: "valid" }),
  "login-empty": entry(WfAccessCode, { variant: "empty" }),
  "login-create": entry(WfAccessCode, { variant: "create" }),
  "auth-success": entry(WfAuthSuccess),
  onboarding: entry(WfOnboarding, { step: 0 }),
  "onboarding-intro": entry(WfOnboarding, { variant: "intro" }),
  "onboarding-2": entry(WfOnboarding, { step: 1 }),
  "onboarding-3": entry(WfOnboarding, { step: 2 }),
  guidance: entry(WfGuidance),
  neurotype: entry(WfNeurotype, { variant: "question" }),
  "neurotype-complete": entry(WfNeurotype, { variant: "complete" }),
  profile: entry(WfProfile),
  "onboarding-complete": entry(WfOnboardingComplete),
  library: entry(WfLibrary, { variant: "home" }),
  "library-dark": entry(WfLibrary, { variant: "browse" }),
  "library-categories": entry(WfLibrary, { variant: "categories" }),
  "library-search": entry(WfLibrary, { variant: "search" }),
  "library-search-results": entry(WfLibrary, { variant: "search-results" }),
  "library-filters": entry(WfLibrary, { variant: "filters" }),
  "library-empty": entry(WfLibrary, { variant: "empty" }),
  "library-no-assigned": entry(WfLibrary, { variant: "no-assigned" }),
  favorites: entry(WfFavorites),
  "detail-overview": entry(WfSessionDetail, { variant: "overview" }),
  detail: entry(WfSessionDetail, { variant: "detail" }),
  "detail-available": entry(WfSessionDetail, { variant: "available" }),
  "detail-downloaded": entry(WfSessionDetail, { variant: "downloaded" }),
  "detail-concept": entry(WfSessionDetail),
  "player-idle": entry(WfPlayer, { variant: "idle" }),
  player: entry(WfPlayer, { variant: "playing" }),
  "player-paused": entry(WfPlayer, { variant: "paused" }),
  "player-completed": entry(WfPlayer, { variant: "completed" }),
  "player-background": entry(WfPlayer, { variant: "background" }),
  "player-concept": entry(WfPlayer, { variant: "playing" }),
  completion: entry(WfCompletion),
  "completion-reflection": entry(WfCompletionReflection),
  "feedback-rating": entry(WfFeedback, { variant: "rating" }),
  feedback: entry(WfFeedback, { variant: "form" }),
  "feedback-submitted": entry(WfFeedback, { variant: "submitted" }),
  about: entry(WfAbout),
  "about-privacy": entry(WfAbout, { variant: "privacy" }),
  "science-support": entry(WfScienceHome),
  research: entry(WfResearch),
  support: entry(WfSupport),
  "support-contact": entry(WfSupport, { variant: "contact" }),
  settings: entry(WfSettings),
  "system-loading": entry(WfSystemLoading),
  "error-network": entry(WfError, { variant: "network" }),
  "error-session": entry(WfError, { variant: "session" }),
  "error-invalid-invitation": entry(WfError, { variant: "invalid-invitation" }),
  "error-expired-invitation": entry(WfError, { variant: "expired-invitation" }),
  "error-access-revoked": entry(WfError, { variant: "access-revoked" }),
  "error-server": entry(WfError, { variant: "server" }),
  "error-maintenance": entry(WfError, { variant: "maintenance" }),
  "partner-login": entry(WfPartnerLogin, {}, DESKTOP_FRAME),
  "partner-dashboard": entry(WfPartnerDashboard, {}, DESKTOP_FRAME),
  "partner-org-settings": entry(WfPartnerDashboard, { variant: "org-settings" }, DESKTOP_FRAME),
  "partner-invite": entry(WfAdminTable, { title: "Invite listener" }, DESKTOP_FRAME),
  "partner-roster": entry(WfAdminTable, { title: "Listener roster" }, DESKTOP_FRAME),
  "partner-listener-detail": entry(WfPartnerListenerDetail, {}, DESKTOP_FRAME),
  "admin-sessions": entry(WfAdminTable, { title: "Session management" }, DESKTOP_FRAME),
  "admin-listeners": entry(WfAdminTable, { title: "Listener management" }, DESKTOP_FRAME),
  "admin-organisations": entry(WfAdminTable, { title: "Organisation management", variant: "organisations" }, DESKTOP_FRAME),
  "admin-assignment": entry(WfAdminTable, { title: "Session assignment", variant: "assignment" }, DESKTOP_FRAME),
  "admin-analytics": entry(WfAdminTable, { title: "Dashboard" }, DESKTOP_FRAME),
  "admin-analytics-detail": entry(WfAdminTable, { title: "Analytics", variant: "analytics" }, DESKTOP_FRAME),
  "pv-topic-hifi": entry(WfTopicDetail),
};

export function resolveWireframe(key) {
  return WIREFRAME_REGISTRY[key] ?? null;
}

export function getWireframeFrame(key) {
  return WIREFRAME_REGISTRY[key]?.frame ?? "mobile";
}
