/**
 * Key screens catalogue — four tiers, five layout concepts per screen.
 * Concept A is the canonical baseline from flows; B–E are exploration directions.
 */

function c(id, letter, name, tagline, idea, best, watchout, wireframeKey = null) {
  return { id, letter, name, tagline, idea, best, watchout, wireframeKey };
}

function screen(id, title, purpose, screenKey, concepts) {
  return { id, title, purpose, screenKey, concepts };
}

/** @type {import("./keyScreensCatalogue.js").KeyScreenTier[]} */
export const KEY_SCREEN_TIERS = [
  {
    id: "key-screens-tier-1",
    tier: "Tier 1",
    label: "Core Product",
    title: "Core product",
    description:
      "The daily listening loop — home, browse, detail, play, and completion. Each screen holds five layout directions; concept A is the flow baseline.",
    screens: [
      screen(
        "home",
        "Home",
        "Primary hub answering what should I play now — resume, next session, and progress at a glance.",
        "library",
        [
          c(
            "a",
            "A",
            "Library-first list",
            "Greeting · chips · session rows",
            "Greeting, category chips, and scannable rows with resume as the first item. Familiar streaming-app browse pattern.",
            "Listeners with several assigned sessions who browse and filter.",
            "Play/resume can feel buried if rows compete with filters.",
          ),
          c(
            "b",
            "B",
            "Player-first hero",
            "One-tap resume · minimal chrome",
            "Large centred artwork, session title, time remaining, and a single play control. Browse is a text link, not a competing CTA.",
            "Clinical contexts with one recommended session per day.",
            "Under-serves listeners with a real library to explore.",
            "library",
          ),
          c(
            "c",
            "C",
            "Protocol day plan",
            "Ordered steps · completion ticks",
            "Day N header with ordered checklist — tap any step to open detail and play. Sequence and completion read first.",
            "Regiment and workplace programmes where order matters.",
            "Protocols are limited in v1 — may over-promise scope.",
          ),
          c(
            "d",
            "D",
            "Grid + centre play",
            "2-column grid · raised play FAB",
            "Filter chips and a 2-column session grid. Raised centre nav play always resumes the current session.",
            "Mixed libraries where browse and one-tap resume both matter.",
            "Five destinations plus FAB can feel heavy on small phones.",
          ),
          c(
            "e",
            "E",
            "Learn + listen hub",
            "Resume · science teaser · rows",
            "Resume card first, then a learn article teaser, then session rows. Science content rotates from the public visitor CMS.",
            "Science-curious listeners and credibility-forward partners.",
            "Broadest home surface — most to build and maintain.",
          ),
        ],
      ),
      screen(
        "session-library",
        "Session Library",
        "Full provisioned catalogue — every session assigned to this listener, filterable and scannable.",
        "library-dark",
        [
          c(
            "a",
            "A",
            "Scannable list",
            "Rows · duration · assigned badge",
            "Default list with duration, neurotype tags, and trailing play affordance. Category chips filter in place.",
            "8+ sessions where listeners compare before playing.",
            "Long lists need virtualisation — provisioned sets are bounded but still scroll.",
          ),
          c(
            "b",
            "B",
            "Compact list",
            "Title · duration only",
            "Reduced metadata — title and duration only, no artwork thumbnails. Fastest scan for repeat listeners.",
            "Listeners who already know their assigned sessions.",
            "Harder to distinguish sessions at a glance.",
          ),
          c(
            "c",
            "C",
            "Grouped sections",
            "Morning · midday · evening",
            "Sessions grouped by time-of-day or use case with sticky section headers.",
            "Protocol-adjacent programmes with time-based listening.",
            "Grouping logic must stay honest — not all partners assign by time.",
          ),
          c(
            "d",
            "D",
            "Artwork grid",
            "2-column cards · filter chips",
            "2-column grid with artwork, title, and filter chips above. Visual browse before play.",
            "Visual learners and larger provisioned libraries.",
            "Grid uses more vertical space — fewer rows above fold.",
            "library",
          ),
          c(
            "e",
            "E",
            "Search-first",
            "Search bar · recent · favourites",
            "Prominent search with recent and saved shortcuts below. List results replace browse when typing.",
            "Power users with 15+ assigned sessions.",
            "Search adds build scope — validate need before v1.",
            "favorites",
          ),
        ],
      ),
      screen(
        "session-detail",
        "Session Detail",
        "Pre-play briefing — purpose, duration, neurotype fit, and benefits before the player opens.",
        "detail",
        [
          c(
            "a",
            "A",
            "Hero + metadata",
            "Artwork · tags · sticky play",
            "Full-width artwork hero, title, duration pill, tag row, benefits bullets, and sticky Play CTA on scroll.",
            "Default high-fidelity direction — sets expectations clearly.",
            "Hero parallax should disable when reduced motion is on.",
          ),
          c(
            "b",
            "B",
            "Clinical sheet",
            "Indication · duration · when to use",
            "Top half artwork; bottom sheet with structured fields: indication, duration, when to use, contraindications.",
            "Regulated partner contexts needing explicit use guidance.",
            "Sheet snap points add interaction complexity.",
          ),
          c(
            "c",
            "C",
            "Minimal soundcard",
            "Square art · two lines · play",
            "Square artwork left, title and duration right, two-line description, full-width Play. No scroll for standard sessions.",
            "Listeners who already know their library — confirm-only.",
            "Long descriptions need expand — keep copy tight.",
          ),
          c(
            "d",
            "D",
            "Story + preview",
            "Narrative · 30s preview · play",
            "Narrative paragraph, inline 30-second preview player, then full Play. Helps first-time play of unfamiliar sessions.",
            "First play of unfamiliar assigned sessions.",
            "Preview counts as a stream — needs analytics and stop-on-scroll.",
          ),
          c(
            "e",
            "E",
            "Comparison mode",
            "Side-by-side · recommended badge",
            "When arriving from choose between similar, show side-by-side duration and benefit diff with recommended badge.",
            "Partners assigning overlapping sessions in the same category.",
            "Compare mode is an edge case — keep single-session view simple.",
          ),
        ],
      ),
      screen(
        "player",
        "Player",
        "Full-screen listening with minimal chrome — sound leads, controls recede.",
        "player",
        [
          c(
            "a",
            "A",
            "Full-bleed ambient",
            "Gradient art · play/pause · progress",
            "Edge-to-edge gradient artwork, centred play/pause, thin progress bar, swipe down to minimise.",
            "Default brand moment — matches PRD hi-fi direction.",
            "Busy animation during listen fights the calm product promise.",
          ),
          c(
            "b",
            "B",
            "Timer-forward",
            "Large countdown · no scrubber",
            "Large remaining-time numerals, small title, play/pause only — no scrubber for timed regulation sessions.",
            "Fixed-duration regulation and clinical sessions.",
            "Listeners expect scrub on longer sessions — make it session-type aware.",
          ),
          c(
            "c",
            "C",
            "Breath-sync visual",
            "Subtle pulse · tap to toggle",
            "Subtle expanding circle or waveform tied to audio envelope — not a literal breath pacer unless required.",
            "Sessions with guided pacing or breath cues.",
            "Must respect reduced motion — static artwork fallback required.",
          ),
          c(
            "d",
            "D",
            "Caption rail",
            "Collapsible transcript · play/pause",
            "Optional collapsible transcript for sessions with spoken guidance. Default collapsed; expands for accessibility.",
            "Instructed sessions and clinical clarity.",
            "Transcript sync highlight is v2 — ship read-only first.",
          ),
          c(
            "e",
            "E",
            "Mini-player browse",
            "Full player · persistent mini pill",
            "On background, persistent mini-player pill above bottom nav — tap to expand. Supports browse-while-listening.",
            "Learn + listen and library-first models.",
            "Mini player must not appear on onboarding surfaces.",
            "pv-listening",
          ),
        ],
      ),
      screen(
        "session-complete",
        "Session Complete",
        "Completion moment — celebrate finish, route to reflection or back to library.",
        "completion",
        [
          c(
            "a",
            "A",
            "Quiet completion",
            "Checkmark · done · continue",
            "Simple checkmark, session title, Done and Continue listening actions. Calm, not gamified.",
            "Daily regulation listeners who complete often.",
            "Too minimal may feel anticlimactic for milestone sessions.",
          ),
          c(
            "b",
            "B",
            "Reflection prompt",
            "How do you feel? · skip",
            "Immediate mood scale before returning — mirrors public visitor reflection. Skippable in one tap.",
            "Continuity between public sample and provisioned app.",
            "Never block return to library — feedback is optional.",
            "feedback",
          ),
          c(
            "c",
            "C",
            "Progress update",
            "Streak · minutes · next up",
            "Shows listening streak, minutes today, and suggested next session card.",
            "Habit-building workplace programmes.",
            "Stats can feel gamified — keep tone clinical and private.",
          ),
          c(
            "d",
            "D",
            "Partner message",
            "Care team note · continue",
            "Optional partner-configured message: Well done — same time tomorrow? Single dismiss CTA.",
            "B2B programmes with coach or clinician oversight.",
            "Partner copy must be CMS-driven — no hard-coded messages.",
          ),
          c(
            "e",
            "E",
            "Auto-advance",
            "2s fade · next session",
            "Brief completion animation then auto-opens next session in plan or returns to home.",
            "Protocol-led day plans with ordered steps.",
            "Auto-advance needs cancel — accidental chaining is costly.",
          ),
        ],
      ),
    ],
  },
  {
    id: "key-screens-tier-2",
    tier: "Tier 2",
    label: "Getting Users In",
    title: "Getting users in",
    description:
      "Cold start through first listen — splash, guest entry, invite redemption, login, onboarding welcome, and listening guidance.",
    screens: [
      screen(
        "splash",
        "Splash",
        "Brand moment on cold start — loading, entitlement check, and route to the right entry path.",
        "splash",
        [
          c(
            "a",
            "A",
            "Wordmark hold",
            "Logo · fade · route",
            "Centred Sonocea wordmark on paper, brief hold, fade to next route. No animation beyond opacity.",
            "Premium restraint — matches sound-first brand.",
            "Feels static if load takes longer than 2s — need skeleton handoff.",
          ),
          c(
            "b",
            "B",
            "Ambient pulse",
            "Logo · subtle breathe",
            "Wordmark with subtle spectral breathe animation while auth and config resolve.",
            "Brand differentiation at first open.",
            "Must honour prefers-reduced-motion — static fallback.",
          ),
          c(
            "c",
            "C",
            "Partner co-brand",
            "Partner mark · Sonocea lockup",
            "When deep-linked from partner invite, show partner logo above Sonocea wordmark. Seat context loads quietly.",
            "B2B invites where organisation context matters.",
            "Partner logo must not overpower Sonocea trust mark.",
          ),
          c(
            "d",
            "D",
            "Progress load",
            "Logo · thin progress bar",
            "Wordmark with indeterminate progress bar when cold start exceeds 1.5s.",
            "Slow networks and large config fetches.",
            "Progress bar implies determinism — use indeterminate only.",
          ),
          c(
            "e",
            "E",
            "Skip to content",
            "Instant cut · returning user",
            "No splash for returning authenticated users — straight to last route or home.",
            "Daily reopen — respect listener time.",
            "First-time users still need brand moment — gate by session count.",
          ),
        ],
      ),
      screen(
        "welcome-guest",
        "Welcome / Guest Landing",
        "Entry decision for unauthenticated visitors — discover the sample experience or sign in with an invite.",
        "pv-get-started",
        [
          c(
            "a",
            "A",
            "Dual path",
            "Discover · sign in",
            "Two equal paths: Try a sample session and Sign in with invite. Science credibility line above CTAs.",
            "Mixed traffic — public curious and invited listeners.",
            "Two equal CTAs can paralyse — test primary emphasis.",
          ),
          c(
            "b",
            "B",
            "Sample-first",
            "Hero · start listening",
            "Single primary Start listening CTA with sign in as tertiary text link. Sample is the default path.",
            "Marketing-driven acquisition and science demos.",
            "Invited listeners may miss sign in — surface invite link clearly.",
            "pv-discover",
          ),
          c(
            "c",
            "C",
            "Invite-first",
            "Partner context · redeem",
            "Leads with Your organisation invited you — redeem code primary, discover secondary.",
            "Partner email and QR campaigns.",
            "Public discoverers may feel excluded — keep discover visible.",
            "pv-invitation",
          ),
          c(
            "d",
            "D",
            "Returning recognition",
            "Welcome back · continue",
            "Recognises returning device with Welcome back and Continue where you left off before auth paths.",
            "Clinic iPads and shared household devices.",
            "Privacy — confirm identity before showing session data.",
            "pv-returning-home",
          ),
          c(
            "e",
            "E",
            "Science gate",
            "Headline · evidence · enter",
            "Short science headline and 20-word value prop above entry CTAs — borrows public visitor credibility.",
            "Science-curious visitors from content marketing.",
            "Adds scroll before action — keep copy under 40 words.",
          ),
        ],
      ),
      screen(
        "accept-invitation",
        "Accept Invitation",
        "Deep-link entry from partner invite — redeem code, validate entitlement, route to account creation.",
        "pv-invitation",
        [
          c(
            "a",
            "A",
            "Partner-branded landing",
            "Org name · code field · continue",
            "Partner mark above invite-code field and primary Continue. Organisation name and seat expiry as quiet metadata.",
            "Co-branded partner communications.",
            "Partner logo max 48px — Sonocea wordmark stays primary.",
          ),
          c(
            "b",
            "B",
            "Minimal code + Apple ID",
            "Code field · Apple · email link",
            "Black canvas, centred mono invite field, outline Apple button, email as tertiary link. No carousel.",
            "Fastest path for iPhone invite holders.",
            "Android listeners need equal-weight Google or email path.",
            "login-empty",
          ),
          c(
            "c",
            "C",
            "Redeem / sign-in tabs",
            "Segmented · returning users",
            "Segmented control: Redeem invite | Sign in. Returning listeners skip code entry.",
            "Shared devices serving multiple listeners.",
            "Tab memory on return visits — persist last segment.",
            "login",
          ),
          c(
            "d",
            "D",
            "QR deep redeem",
            "Scan · manual fallback",
            "Camera scan for QR invites plus collapsed manual code fallback. Clinical tone: Your care team invited you.",
            "Clinic-printed cards and emailed magic links.",
            "Camera permission rationale before opening scanner.",
          ),
          c(
            "e",
            "E",
            "Science teaser gate",
            "Value prop · code · continue",
            "Short science teaser above invite field — bridges visitors who skimmed public content.",
            "Invited participants who discovered Sonocea publicly first.",
            "Teaser must not repeat in onboarding — one-time only.",
          ),
        ],
      ),
      screen(
        "login",
        "Login",
        "Returning listener sign in — email, Apple ID, and password with invite context when applicable.",
        "login-empty",
        [
          c(
            "a",
            "A",
            "Email + password",
            "Email · password · sign in",
            "Standard email and password with forgot password link. Invite context banner when arriving from redeem.",
            "Returning listeners on any platform.",
            "Password fatigue in clinical cohorts — offer biometrics after first sign-in.",
          ),
          c(
            "b",
            "B",
            "Apple-first",
            "Apple · email fallback",
            "Sign in with Apple as primary, email as text link. Minimal chrome, keyboard opens on email path.",
            "iPhone-heavy partner programmes.",
            "Apple-only primary alienates Android — match platform.",
            "login",
          ),
          c(
            "c",
            "C",
            "Magic link",
            "Email · send link",
            "Email only — send magic link, no password. Check your email holding state.",
            "Low-friction clinical and older adult cohorts.",
            "Email deliverability and link expiry UX must be solid.",
          ),
          c(
            "d",
            "D",
            "Biometric unlock",
            "Face ID · password fallback",
            "Returning device shows Face ID / Touch ID with Use password fallback. No email field until fallback.",
            "Daily reopen on personal devices.",
            "First sign-in still needs full auth — gate by credential presence.",
          ),
          c(
            "e",
            "E",
            "Organisation SSO",
            "SSO button · email fallback",
            "Sign in with your organisation SSO when partner configures SAML — email fallback below.",
            "Enterprise workplace deployments.",
            "SSO is partner-specific — hide when not configured.",
          ),
        ],
      ),
      screen(
        "welcome-sonocea",
        "Welcome to Sonocea",
        "Personalised onboarding welcome — what Sonocea is, how listening works, and what happens next.",
        "onboarding",
        [
          c(
            "a",
            "A",
            "Card carousel",
            "Swipe cards · dot progress",
            "Horizontal swipe cards: How listening works → Headphones → Your neurotype → Your library. Skip top-right.",
            "Familiar wellness-app onboarding pattern.",
            "Cap at 4–6 steps — avoid gamified step counts.",
          ),
          c(
            "b",
            "B",
            "Single scroll story",
            "Vertical blocks · sticky CTA",
            "One continuous vertical scroll with headline blocks separated by hairlines. Sticky footer CTA after 60% scroll.",
            "Lowest cognitive load for regulation-focused listeners.",
            "Long scroll on small phones — keep sections short.",
            "onboarding-2",
          ),
          c(
            "c",
            "C",
            "Video + checklist",
            "60s intro · tick boxes",
            "Short hosted video then interactive checklist: quiet space, headphones, 10+ minutes available.",
            "Partners wanting consistent onboarding message.",
            "Video skippable after 10s — captions on by default.",
            "onboarding-3",
          ),
          c(
            "d",
            "D",
            "Clinical brief",
            "Assigned plan · how to use",
            "Structured brief: your listening plan, how to use Sonocea, when to listen, what to expect.",
            "Hospital and workplace prescribed listening.",
            "No skip in regulated contexts — partner configurable.",
          ),
          c(
            "e",
            "E",
            "Conversational coach",
            "Chat bubbles · tap advance",
            "Chat-bubble sequence from Sonocea guide — one message at a time with tap-to-advance. Personalised with first name.",
            "Younger neurodiverse cohorts.",
            "Typing indicator max 800ms — do not fake long delays.",
          ),
        ],
      ),
      screen(
        "listening-guidance",
        "Listening Guidance",
        "Operational listening literacy — headphones, environment, duration, and when to listen.",
        "guidance",
        [
          c(
            "a",
            "A",
            "Illustrated tips",
            "Headphones · space · duration",
            "Three illustrated cards: use headphones, find quiet space, allow full duration. Primary Continue when all acknowledged.",
            "First-time listeners before first playback.",
            "Illustrations need text labels — not illustration-only.",
          ),
          c(
            "b",
            "B",
            "Checklist gate",
            "Tick to continue · no skip",
            "Interactive checklist items must be ticked before Continue enables. No honour system.",
            "Clinical contexts requiring explicit acknowledgement.",
            "Too rigid for returning listeners — allow skip on repeat.",
          ),
          c(
            "c",
            "C",
            "Inline on player",
            "First-play overlay · dismiss",
            "Guidance appears as first-play overlay on player, not standalone screen. Dismiss saves preference.",
            "Reducing onboarding screen count.",
            "Critical safety info may be missed if dismissed hastily.",
          ),
          c(
            "d",
            "D",
            "Audio walkthrough",
            "30s audio guide · continue",
            "Optional 30-second audio guide explaining how to listen — play/pause with continue when done.",
            "Listeners who struggle with text-heavy instructions.",
            "Auto-play audio needs consent — default paused.",
          ),
          c(
            "e",
            "E",
            "Partner custom",
            "Clinician note · standard tips",
            "Partner-configured note from care team above standard headphone and environment tips.",
            "B2B programmes with specific listening protocols.",
            "Partner copy length must be capped — link out for detail.",
          ),
        ],
      ),
    ],
  },
  {
    id: "key-screens-tier-3",
    tier: "Tier 3",
    label: "Public Experience",
    title: "Public experience",
    description:
      "Unauthenticated visitor journey — sample listening, reflection, science, and access request. Reuses patterns that may carry into the provisioned app.",
    screens: [
      screen(
        "public-landing",
        "Public Landing",
        "Introduce the curated sample experience — what Sonocea offers before account creation.",
        "pv-get-started",
        [
          c(
            "a",
            "A",
            "Science-led hero",
            "Headline · sample CTA",
            "Evidence-based headline, 2-line value prop, primary Try a 5-minute sample CTA.",
            "Content marketing and conference demos.",
            "Keep above fold on iPhone SE — test copy length.",
          ),
          c(
            "b",
            "B",
            "Sound-first",
            "Waveform · start listening",
            "Animated waveform hero with immediate Start listening — minimal copy.",
            "Sound-first brand differentiation.",
            "Animation must respect reduced motion.",
            "pv-discover",
          ),
          c(
            "c",
            "C",
            "Check-in first",
            "How are you feeling? · begin",
            "Opens with nervous-system check-in before sample — personalises session recommendation.",
            "Demonstrating personalisation value publicly.",
            "Adds friction before sample — make skippable.",
            "pv-check-in",
          ),
          c(
            "d",
            "D",
            "Social proof",
            "Partner logos · sample CTA",
            "Partner and clinical logos above sample CTA — credibility before experience.",
            "B2B sales-assisted visitor flows.",
            "Logo wall needs permission — no fabricated endorsements.",
          ),
          c(
            "e",
            "E",
            "Returning visitor",
            "Continue sample · sign in",
            "Recognises prior sample progress with Continue your sample and sign in link.",
            "Multi-visit public visitors before access request.",
            "Device storage for progress — clear privacy note.",
            "pv-returning-home",
          ),
        ],
      ),
      screen(
        "check-in",
        "Check-In",
        "Baseline state capture before sample — how regulated or activated the visitor feels right now.",
        "pv-check-in",
        [
          c(
            "a",
            "A",
            "Slider spectrum",
            "Dysregulated ← → regulated",
            "Single horizontal slider with labelled endpoints. No numeric score shown to visitor.",
            "Fast baseline capture — mirrors post-sample reflection.",
            "Endpoints need text labels for screen readers.",
          ),
          c(
            "b",
            "B",
            "Emoji faces",
            "Five faces · tap one",
            "Five face icons from dysregulated to regulated — tap to select. Familiar pattern from wellness apps.",
            "Visitors uncomfortable with slider precision.",
            "Faces must have text labels — not emoji-only.",
          ),
          c(
            "c",
            "C",
            "Word chips",
            "Anxious · calm · focused · tired",
            "Multi-select word chips — select all that apply. Maps to session recommendation.",
            "Nuanced self-report without clinical labels.",
            "Chip selection UX on small screens — wrap cleanly.",
          ),
          c(
            "d",
            "D",
            "Body map",
            "Tap where you feel tension",
            "Simple body outline — tap areas of tension. Optional for public v1.",
            "Somatic-focused regulation contexts.",
            "High build cost — validate before committing.",
          ),
          c(
            "e",
            "E",
            "Skip with default",
            "Skip · recommend default session",
            "Skip check-in uses default regulation session — no blocking gate.",
            "Low-friction demo environments.",
            "Loses personalisation story — note in analytics.",
          ),
        ],
      ),
      screen(
        "sample-session-player",
        "Sample Session Player",
        "Five-minute public sample playback — core sound experience before sign-up.",
        "pv-listening",
        [
          c(
            "a",
            "A",
            "Full-bleed sample",
            "Ambient art · minimal controls",
            "Same player chrome as provisioned app but time-capped at 5 minutes. Exit returns to reflection.",
            "Continuity between public and provisioned experience.",
            "Sample must not expose full session library.",
          ),
          c(
            "b",
            "B",
            "Guided intro overlay",
            "10s intro · then play",
            "Brief this is a sample overlay before playback starts — auto-dismiss or tap to skip.",
            "First-time visitors unfamiliar with structured sound.",
            "Overlay timing — skippable after 3s minimum.",
          ),
          c(
            "c",
            "C",
            "Headphones gate",
            "Plug in headphones · play",
            "Headphones prompt inline before play enables — matches listening guidance intent.",
            "Ensuring proper listening conditions in demos.",
            "Bluetooth detection unreliable — honour system with copy.",
            "pv-headphones",
          ),
          c(
            "d",
            "D",
            "Timer visible",
            "Countdown · sample ends",
            "Prominent sample time remaining — sets expectation that this is a preview.",
            "Managing expectations before access request.",
            "Countdown anxiety — keep visual calm.",
          ),
          c(
            "e",
            "E",
            "Science captions",
            "What you're hearing · play",
            "Collapsible what you're hearing science line during sample playback.",
            "Education-forward public journey.",
            "Captions must not compete with listen — default collapsed.",
            "player",
          ),
        ],
      ),
      screen(
        "reflection",
        "Reflection",
        "Post-sample mood capture — before/after comparison and gentle route toward science or access.",
        "pv-reflection",
        [
          c(
            "a",
            "A",
            "After-only scale",
            "How do you feel now?",
            "Single post-sample mood scale with Done and Explore science actions.",
            "Fastest completion — lowest friction.",
            "Loses before/after story without check-in data.",
          ),
          c(
            "b",
            "B",
            "Before / after",
            "Your shift · visual delta",
            "Shows check-in baseline vs now on same axis with visual delta arrow.",
            "Demonstrating value in partner demos.",
            "Requires check-in data — graceful fallback if skipped.",
            "pv-check-in",
          ),
          c(
            "c",
            "C",
            "Optional note",
            "Mood · one-line journal",
            "Mood scale plus optional 140-character note — private, not shared.",
            "Engaged visitors who want to capture the moment.",
            "Keyboard cover on small phones — scroll affordance.",
          ),
          c(
            "d",
            "D",
            "Science bridge",
            "Mood · why it works",
            "After mood capture, inline why you might feel different science snippet with link to full overview.",
            "Visitors ready to go deeper after feeling an effect.",
            "Science must not feel like a sales pitch.",
            "pv-science-home",
          ),
          c(
            "e",
            "E",
            "Request access CTA",
            "Mood · get access",
            "Mood capture then prominent Request access for your organisation CTA.",
            "B2B funnel terminus after positive sample.",
            "Not all visitors are organisational buyers — keep science path.",
            "pv-request-access",
          ),
        ],
      ),
      screen(
        "science-overview",
        "Science Overview",
        "Evidence-based explanation hub — how structured sound affects the nervous system.",
        "pv-science-home",
        [
          c(
            "a",
            "A",
            "Topic cards",
            "Nervous system · sleep · focus",
            "Scannable topic cards linking to article detail. Reused in provisioned Learn tab.",
            "Default science hub — single CMS source.",
            "Article count must stay bounded — curate, don't dump.",
          ),
          c(
            "b",
            "B",
            "Single long read",
            "One scroll · anchor nav",
            "One long-form article with sticky anchor nav — no topic grid.",
            "Conference kiosk and quick demo contexts.",
            "Harder to maintain one monolithic article.",
            "pv-topic-detail",
          ),
          c(
            "c",
            "C",
            "Video + summary",
            "60s explainer · read more",
            "Hosted video with three bullet summary and read the research link.",
            "Visual learners and partner presentations.",
            "Video load on cellular — poster frame required.",
          ),
          c(
            "d",
            "D",
            "FAQ accordion",
            "Common questions · evidence",
            "Accordion of common questions with citation footnotes.",
            "Skeptical clinical audiences.",
            "Citations must be real — link to publications.",
            "research",
          ),
          c(
            "e",
            "E",
            "Personalised teaser",
            "Based on your check-in",
            "Science content filtered by check-in mood — e.g. regulation-focused articles first.",
            "Visitors who completed check-in.",
            "Fallback to default hub when check-in skipped.",
          ),
        ],
      ),
      screen(
        "request-access",
        "Request Access",
        "Organisational interest form — capture buyer intent after positive sample experience.",
        "pv-request-access",
        [
          c(
            "a",
            "A",
            "Short form",
            "Org · email · role · submit",
            "Organisation name, work email, role, and submit. Confirmation screen with next steps.",
            "Fast B2B lead capture.",
            "Validate work email format — no personal gmail emphasis.",
          ),
          c(
            "b",
            "B",
            "Progressive form",
            "Step 1 · org → contact",
            "Two-step: organisation details then contact details. Progress indicator.",
            "Higher-quality leads with less form fatigue per step.",
            "More screens in funnel — test completion rate.",
          ),
          c(
            "c",
            "C",
            "Calendar book",
            "Form · book a call",
            "Short form plus Book a 15-minute call embedded scheduler.",
            "Sales-assisted enterprise deals.",
            "Scheduler embed adds third-party dependency.",
          ),
          c(
            "d",
            "D",
            "Partner referral",
            "Already have a code? · request",
            "Primary path for buyers without code; secondary Already have an invite code links to redeem.",
            "Mixed visitor types on same screen.",
            "Two paths need clear visual hierarchy.",
            "pv-invitation",
          ),
          c(
            "e",
            "E",
            "Mailto fallback",
            "Email us · template",
            "Single CTA opens mailto with pre-filled template including sample completion timestamp.",
            "Fastest v1 ship without backend form.",
            "Poor analytics — last resort only.",
          ),
        ],
      ),
    ],
  },
  {
    id: "key-screens-tier-4",
    tier: "Tier 4",
    label: "Supporting",
    title: "Supporting",
    description:
      "Account, credibility, and help surfaces — sparse hierarchy, premium tone. Listeners are here to listen, not configure.",
    screens: [
      screen(
        "about-sonocea",
        "About Sonocea",
        "Mission, science summary, team, version, and legal links — credibility without investor-deck length.",
        "about",
        [
          c(
            "a",
            "A",
            "Mission scroll",
            "Mission · science · legal",
            "Short mission, three science bullets, link to full science hub, legal links footer.",
            "Default credibility pack.",
            "Scroll under 2 screens — scannable only.",
          ),
          c(
            "b",
            "B",
            "Clinical fact sheet",
            "What it is · what it isn't",
            "Structured facts: what Sonocea is, what it is not, evidence summary, contact.",
            "Clinical partner due diligence.",
            "Not does not diagnose — plain language required.",
          ),
          c(
            "c",
            "C",
            "Inline web",
            "Open sonocea.com/about",
            "Single row in settings opens about page in in-app browser — no duplicate content.",
            "Lowest build and maintenance cost.",
            "Offline shows cached paragraph only.",
          ),
          c(
            "d",
            "D",
            "Team voices",
            "Founder · scientist quote",
            "Founder quote and lead scientist card — humanises brand.",
            "Premium brand building.",
            "Photos optional — quote max 2 sentences.",
          ),
          c(
            "e",
            "E",
            "Legal-first",
            "Privacy · terms · licenses",
            "About is legal-heavy: privacy, terms, licenses, analytics opt-out.",
            "Privacy-sensitive deployments.",
            "Plain language summaries above legalese.",
          ),
        ],
      ),
      screen(
        "science-library",
        "Science Library",
        "In-app science CMS — articles, topics, and citations for listeners and visitors.",
        "science-support",
        [
          c(
            "a",
            "A",
            "Topic grid",
            "Cards · read time · topic",
            "Topic cards with read time and category. Same CMS as public science overview.",
            "Reuse across public and provisioned Learn tab.",
            "Keep article count bounded — curate topics.",
          ),
          c(
            "b",
            "B",
            "Featured + list",
            "Hero article · more below",
            "One featured article hero with list of recent below.",
            "Highlighting new research publications.",
            "Featured rotation needs CMS scheduling.",
            "pv-science-home",
          ),
          c(
            "c",
            "C",
            "Search science",
            "Search · filters · results",
            "Search bar with topic filters — results list.",
            "Large article libraries in later phases.",
            "Search is v2 unless article count exceeds 20.",
          ),
          c(
            "d",
            "D",
            "Audio articles",
            "Listen · read · 5 min",
            "Articles with optional audio narration — headphone icon on cards.",
            "Accessibility and listen-first brand.",
            "Narration production cost — start with top 5 articles.",
          ),
          c(
            "e",
            "E",
            "Partner pack",
            "Curated for your org",
            "Partner-configured article subset — Your organisation's resources header.",
            "B2B programmes with custom science packs.",
            "Fallback to full library when no partner config.",
            "pv-topic-detail",
          ),
        ],
      ),
      screen(
        "support",
        "Support",
        "Help listeners resolve playback, access, and account issues — self-serve first, contact when stuck.",
        "support",
        [
          c(
            "a",
            "A",
            "FAQ accordion",
            "Playback · account · plan",
            "Categorised FAQs with Contact us at bottom. Top articles pinned.",
            "Self-serve first — reduces support volume.",
            "Deep link from error states into relevant articles.",
          ),
          c(
            "b",
            "B",
            "Troubleshoot wizard",
            "Can't play → headphones → network",
            "Decision tree: cannot play → check headphones → check network → contact.",
            "Playback issues — most common support topic.",
            "Logs attach on final step — explain what's sent.",
          ),
          c(
            "c",
            "C",
            "Partner triage",
            "Access issue? · partner first",
            "Is this about access from your organisation? Partner contact card first, Sonocea technical second.",
            "B2B entitlement clarity.",
            "Partner contact from CMS — seat ID copy button.",
          ),
          c(
            "d",
            "D",
            "Simple form",
            "What happened? · submit",
            "Single form: what happened plus optional screenshot. Auto-include diagnostics.",
            "Fastest v1 ship.",
            "No FAQ — higher ticket volume.",
          ),
          c(
            "e",
            "E",
            "Contextual help",
            "Help icon per screen",
            "No support tab — help icon on player, login, and profile opens contextual sheet.",
            "Minimal three-tab navigation models.",
            "Profile must aggregate all help entry points.",
          ),
        ],
      ),
      screen(
        "settings",
        "Settings",
        "App preferences — notifications, audio, downloads, and legal links.",
        "settings",
        [
          c(
            "a",
            "A",
            "Grouped list",
            "Account · listening · notifications",
            "iOS-style inset grouped table with chevron rows. Destructive sign out at bottom.",
            "Familiar, fast to build, accessible.",
            "Drill-down depth — keep max 2 levels.",
          ),
          c(
            "b",
            "B",
            "Toggle hub",
            "All toggles · one screen",
            "Single screen with notification, cellular download, and haptics toggles — no drill-down.",
            "Player-first IA with minimal maintenance.",
            "Advanced settings link to web FAQ for edge cases.",
          ),
          c(
            "c",
            "C",
            "Search settings",
            "Search · quick jump",
            "Search bar filters settings rows — quick jump on long lists.",
            "Future-proofing as settings grow.",
            "Overkill for v1 toggle count — defer.",
          ),
          c(
            "d",
            "D",
            "Audio-focused",
            "Playback · quality · downloads",
            "Settings centres audio: quality, download over cellular, sleep timer default.",
            "Listeners who care about playback quality.",
            "Most listeners never open settings — don't block core flows.",
          ),
          c(
            "e",
            "E",
            "Notification-only",
            "Sparse · notifications + legal",
            "Only notification prefs and legal links — everything else in profile.",
            "Three-tab minimal navigation.",
            "Hides needed audio settings — link from player overflow.",
          ),
        ],
      ),
      screen(
        "account",
        "Account",
        "Identity hub — name, organisation, neurotype summary, entitlement, and sign out.",
        "profile",
        [
          c(
            "a",
            "A",
            "Grouped account list",
            "Account · neurotype · partner",
            "Inset grouped list: account details, neurotype summary, provisioning partner, sign out.",
            "Familiar settings pattern.",
            "Neurotype editable — re-runs recommendation sort only.",
          ),
          c(
            "b",
            "B",
            "Profile hub cards",
            "Stats · quick actions",
            "Header with initials avatar, listening stats cards, quick actions grid.",
            "Motivational without gamification.",
            "No leaderboards — private stats only.",
          ),
          c(
            "c",
            "C",
            "Minimal account sheet",
            "Email · partner · sign out",
            "Single screen, no drill-down: email, partner, neurotype chip, notification toggle, sign out.",
            "Player-first IA — max 6 rows visible.",
            "Advanced settings link opens web FAQ.",
          ),
          c(
            "d",
            "D",
            "Entitlement focus",
            "Access via partner · valid until",
            "Prominent card: your access via partner, valid until date, seat ID for support.",
            "Enterprise and clinical transparency.",
            "Renewal CTA only when partner allows self-request.",
          ),
          c(
            "e",
            "E",
            "Listening profile editor",
            "Sliders · live preview",
            "Profile centres neurotype and preference sliders with live library preview.",
            "Personalization as retention driver.",
            "Reset profile needs confirm dialog.",
            "neurotype",
          ),
        ],
      ),
      screen(
        "privacy-policies",
        "Privacy & Policies",
        "Privacy policy, terms of use, licences, and data rights — plain language with legal depth available.",
        "about",
        [
          c(
            "a",
            "A",
            "Policy list",
            "Privacy · terms · licences",
            "Simple list rows opening in-app browser or native scroll views per policy.",
            "Standard compliance pack.",
            "Last updated dates visible on each row.",
          ),
          c(
            "b",
            "B",
            "Plain summary + legal",
            "Summary · full document",
            "Plain-language summary accordion with View full document link per policy.",
            "Listeners who won't read legalese.",
            "Summaries need legal review — not marketing copy.",
          ),
          c(
            "c",
            "C",
            "Export my data",
            "Download · delete account",
            "GDPR-forward: export my data and delete account requests prominent.",
            "EU and clinical data sensitivity.",
            "Delete routes through support in v1 — set expectations.",
          ),
          c(
            "d",
            "D",
            "Analytics opt-out",
            "Toggle · policy link",
            "Analytics opt-out toggle with explanation and policy link.",
            "Privacy-sensitive deployments.",
            "Opt-out must be honoured in v1 if shown.",
          ),
          c(
            "e",
            "E",
            "Web-only legal",
            "Opens sonocea.com/legal",
            "All legal content on web — single row opens browser.",
            "Lowest maintenance.",
            "Offline gap — show short static summary.",
          ),
        ],
      ),
    ],
  },
];

export const KEY_SCREEN_COUNT = KEY_SCREEN_TIERS.reduce(
  (total, tier) => total + tier.screens.length,
  0,
);
